"""Production WSGI entry point.

Import the existing application first so every route, migration and background
loop is registered exactly as before. Then install the narrow runtime adapters
before Gunicorn starts accepting requests.
"""
import dashboard as _dashboard
from evm_to_solana_bridge import install as _install_evm_to_solana_bridge
from wallet_deposit_guidance import install as _install_wallet_deposit_guidance
from app_performance import install as _install_app_performance
from share_canonical_routes import install as _install_share_canonical_routes
from mobile_ui_hotfix import install as _install_mobile_ui_hotfix
from trusted_phantom_autoconnect import install as _install_trusted_phantom_autoconnect
from share_card_concept_d import install as _install_share_card_concept_d
from messages_premium_ui import install as _install_messages_premium_ui
from live_market_deeplink_fix import install as _install_live_market_deeplink_fix

_install_evm_to_solana_bridge(_dashboard)
_install_wallet_deposit_guidance(_dashboard)
_install_app_performance(_dashboard)
_install_share_canonical_routes(_dashboard)
_install_mobile_ui_hotfix(_dashboard)
_install_trusted_phantom_autoconnect(_dashboard)
_install_share_card_concept_d(_dashboard)
_install_messages_premium_ui(_dashboard)
_install_live_market_deeplink_fix(_dashboard)
app = _dashboard.app
