"""Free, first-party platform posts and explicit @orcagent comment replies.

No external model, credentials, market predictions or user-wallet actions.
SQLite publication receipts coordinate all workers and survive restarts.
"""
from __future__ import annotations
import datetime as dt
import os
import re
import sqlite3
import threading
import time
import platform_learning as learning
from zoneinfo import ZoneInfo
from flask import jsonify, request

TZ = ZoneInfo('Europe/Amsterdam')
HOURS = (9, 15, 21)
MENTION = re.compile(r'(?<![\w@])@orcagent(?![\w])', re.I)
LABEL = 'Automated · '
# Approved product copy, not generated claims about prices or user performance.
THESES = (
('calls', 'A token ticker is only the start. A useful call explains the reasoning and records an entry price. Publish your analysis on OrcAgent so others can explore the call and its chart before making their own decision.'),
('community', 'Your trading circle should be your choice. Follow traders whose reasoning interests you, read their calls and ask questions. OrcAgent connects the conversation with the tools to explore a Solana token.'),
('sharing', 'Give your next trading idea some context. Share an OrcAgent call card with its author, recorded entry and a link to the full analysis. The recipient can explore the call and chart in the app.'),
('portfolio', 'A new idea belongs in the context of what you already hold. Use your portfolio alongside the calls and Solana charts you explore on OrcAgent. The decision to trade remains yours.'),
('creators', 'The Creator Rewards pilot connects analysis to qualifying platform activity. Approved creators receive 10% of collected platform fees from eligible buys reached through their calls. Approval and payout checks apply; posting alone does not earn payment.'),
('feedback', 'OrcAgent is growing with its community. If a screen or action gets in your way, tag @orcagent with the feature and what happened. The automated assistant can explain platform functions; account-specific issues need human support.'),
('wallet', 'Connect Phantom to explore OrcAgent with your wallet. Never share your recovery phrase or private key in a post, comment or DM. The platform assistant will never ask for those secrets.'),
('entry', 'A recorded entry gives a call a reference point. It is not a guaranteed execution price or a promise of returns. Read the analysis, explore the chart and make your own decision.'),
('invitations', 'A useful invitation starts with an idea worth discussing. Share a personal call link and track the new accounts and qualifying trades it brings in. Your invitation totals are private.'),
('discussion', 'Good questions make a trading community more useful. Ask what someone is watching and why. OrcAgent puts profiles, calls, reactions and DMs beside the tools to explore Solana tokens.'),
('referrals', 'Invite people who want to explore the community. OrcAgent referrals share 20% of the trading fees generated by attributed users, subject to the referral rules. That is a share of the fee, not their trading volume.'),
('charts', 'A call is an invitation to investigate. Open its analysis, inspect the token and explore the chart. OrcAgent gives the idea a path to the trading tools; you decide whether to take a trade.'),
('transparency', 'A useful call has an author, reasoning and a recorded entry. Keep those details together when you share it. OrcAgent call cards link back to the full call so the context stays within reach.'),
('rewards', 'Creator rewards are tied to actual collected fees from qualifying buys. They are not payments for views or likes. The OrcAgent pilot uses approved participation and manually verified USDC payouts.'),
('follow', 'Build a feed around people whose thinking you want to understand. Follow traders, compare their analyses and continue the conversation in comments or DMs. Explore OrcAgent at your own pace.'),
('privacy', 'Your shared calls can be explored by others. Your invitation dashboard totals are private. OrcAgent keeps the public idea and your personal tracking in their respective places.'),
('costs', 'Review the amount and costs before confirming a trade. Users fund their own transaction costs on OrcAgent. A community call is an opinion, not an instruction to buy.'),
('learning', 'Ask about the reasoning behind an idea. A chart and a call can help you investigate, but no post can guarantee an outcome. OrcAgent connects the tools and conversation so you can decide for yourself.'),
('onboarding', 'New here? Connect Phantom, explore the feed and open a call that interests you. Read the analysis and chart, then follow the traders you want to hear from. Welcome to OrcAgent.'),
('save', 'Sharing a call gives you a personal link and a downloadable card. Use Copy link, Share on X or Save card from the share window. Keep the call context connected when you post it elsewhere.'),
('support', 'Have a question about OrcAgent? Tag @orcagent in a comment and name the feature. The automated assistant answers platform questions and asks for detail when it cannot identify the issue.'),
('creator_scope', 'Creator Rewards is a pilot for approved creators. A qualifying buy must come through the creator’s call and have an actual collected fee. Read the participation and payout details before applying.'),
('portfolio_context', 'Trading tools become more useful with context. Explore community calls and Solana charts, then consider a new idea against your current holdings. OrcAgent brings those steps into the same app.'),
('feedback_loop', 'The people using OrcAgent see where it can improve. Tell us which page you used, which action you tried and what appeared on screen. Useful feedback helps us find the next thing to fix.'),
('share_context', 'A shared ticker should have a way back to the original analysis. OrcAgent call links open the specific call and its chart. Share an idea with the reasoning behind it.'),
('independent', 'Follow an idea without giving up your own judgement. Read the call, explore the chart and consider the costs. OrcAgent provides tools and conversations; you make the trading decision.'),
('social', 'Community is more than a list of tickers. Profiles, follows, comments and DMs help you understand the people behind an idea. Explore the Solana trading community on OrcAgent.'),
('recorded', 'Recorded entry prices preserve the reference point of a call. They do not change into a promise about future performance. Put your analysis alongside that reference when you publish a call.'),
('private_tracking', 'Share a call with your personal invitation link to track the people it brings in. Existing accounts and self-invitations do not count as new accounts. Check Invitations for the rules and your private totals.'),
('fees_not_volume', 'Reward percentages on OrcAgent refer to collected platform fees. They are not percentages of the full trade amount. Read the referral and Creator Rewards rules to understand what qualifies.'),
)

# English platform guidance; both English and Dutch keywords are understood.
FAQ = (
    ('secrets', 'seed|recovery phrase|private key|secret key|herstelzin|priv[eé]sleutel', 'Never post your recovery phrase or private key. Describe your wallet issue without credentials; OrcAgent will never ask for those secrets.'),
    ('bug', 'not working|doesn.t work|error|bug|failed|stuck|werkt niet|fout|mislukt|vast|probleem', 'Which OrcAgent page and action failed? Share the error and your device type so the team can review it. Keep wallet secrets private.'),
    ('creator', 'creator|creators|reward|beloning|verdien|paid|betaald|payout|uitbetaling', 'Approved creators earn 10% of collected fees from qualifying call buys, not views. Read eligibility and payout rules: https://orcagent.fun/creator-rewards. Which part would you like explained?'),
    ('referral', 'referral|referrer|invite|invitation|uitnodig|doorverwijs', 'Referrals share 20% of fees from attributed users, not trade volume. Copy your personal link here: https://orcagent.fun/referrals. Would you like help sharing it?'),
    ('fees', r'\bfees?\b|cost|kost|kosten|percentage|procent|%', 'Reward percentages apply to collected platform fees, not trading volume. You fund transaction costs. Review the costs before confirming; I cannot calculate a personal quote.'),
    ('share', r'\bshare\b|sharing|deel|delen|card|kaart', 'Open a call and tap Share call to copy its link or save its card. Track invitations: https://orcagent.fun/invitations. Are you sharing a link or a card?'),
    ('calls', r'\bcalls?\b|analysis|analyse|entry|instap', 'A call records analysis and an entry reference, not a guaranteed return. Explore a call in the feed: https://orcagent.fun/#app-home. Would you like help reading or publishing one?'),
    ('wallet', 'phantom|connect|login|log.?in|wallet|verbinden|inloggen', 'Tap Connect wallet and approve in Phantom. Return to your chosen browser or PWA. If it fails, share the screen and error, never your recovery phrase.'),
    ('portfolio', 'portfolio|holding|balance|saldo|bezitting', 'Check holdings and activity in Portfolio: https://orcagent.fun/#app-portfolio. Missing something? Tell me which asset and what you see; I cannot access your account.'),
    ('trading', 'trad|buy|sell|swap|kopen|verkopen|ruil|chart|grafiek|solana|chain', 'Explore charts in Live Market: https://orcagent.fun/#app-market. Review costs before confirming a trade. Which platform control would you like help with? I do not recommend tokens or place trades.'),
    ('community', r'follow|volg|\bdm\b|message|bericht|community|feed|comment|reage', 'Follow traders from their profiles, discuss calls in comments or chat in DMs. Tag @orcagent for help with platform features.'),
)

LEARNABLE = {topic:english for topic,pattern,english in FAQ if topic not in ('secrets','bug')}

def answer(message):
    if not isinstance(message, str) or not MENTION.search(message):
        return None
    clean = MENTION.sub('', message).lower()
    token = re.fullmatch(r'\s*(?:do you know\s+|tell me about\s+|what is\s+)?\$?([a-z][a-z0-9_]{1,19})\s+token[\s?!.]*',clean)
    if token:
        symbol = token[1].upper()
        return 'token_choice', LABEL + f"Do you mean ${symbol}? Choose the matching token below, then tell me which OrcAgent feature you want help with."
    for topic, pattern, english in FAQ:
        if re.search(pattern, clean, re.I):
            return topic, LABEL + english
    if re.search(r'benefits?|what (?:can|does)|features?|voordelen|mogelijkheden',clean):
        return 'overview', LABEL + 'OrcAgent brings Solana charts, trading, calls and community into one app. Follow traders, share your analysis and track holdings in Portfolio.'
    if re.fullmatch(r'\s*(?:(?:hi|hello|hey)[\s,!]+)?(?:how are you(?: doing)?|how.s it going|hoe gaat het)[\s!?.,]*',clean):
        return 'welcome', LABEL + "I'm doing well, thanks! How about you? What can I help you with on OrcAgent today?"
    if re.fullmatch(r'\s*(?:hi|hello|hey|hello there|hallo|hoi)[\s!?.,]*',clean):
        return 'welcome', LABEL + "Hey! Welcome to OrcAgent. What would you like to explore today: calls, charts or your portfolio?"
    if re.fullmatch(r"\s*(?:i.m (?:good|fine|well)|good|fine|doing well|thanks|thank you|goed|dank je)(?:[\s,!]+(?:thanks|thank you))?[\s!?.,]*",clean):
        return 'welcome', LABEL + "Thanks for sharing! What would you like to do on OrcAgent today? Explore the feed: https://orcagent.fun/#app-home"
    return 'scope', LABEL + 'Which feature would you like help with: wallet, calls, trading, portfolio or rewards? I can explain OrcAgent, but cannot access your account or predict prices.'

def initialize(db):
    with sqlite3.connect(db, timeout=8) as c:
        learning.initialize(c)
        c.execute("CREATE TABLE IF NOT EXISTS platform_assistant_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL)")
        c.execute("""CREATE TABLE IF NOT EXISTS platform_assistant_events (
            event_key TEXT PRIMARY KEY,kind TEXT NOT NULL,source_user_id INTEGER,
            post_id TEXT,reply_id INTEGER,topic TEXT NOT NULL,created_at REAL NOT NULL)""")
        c.execute('CREATE INDEX IF NOT EXISTS platform_assistant_limits ON platform_assistant_events(kind,source_user_id,created_at)')

def enabled(c, key):
    env = {'posts':'ORCAGENT_PLATFORM_POSTS','replies':'ORCAGENT_PLATFORM_REPLIES','learning':'ORCAGENT_PLATFORM_LEARNING'}[key]
    if os.environ.get(env, '1') == '0':
        return False
    row = c.execute('SELECT value FROM platform_assistant_settings WHERE key=?', (key,)).fetchone()
    return not row or row[0] == '1'

def identity(c):
    pinned = c.execute("SELECT value FROM platform_assistant_settings WHERE key='author_id'").fetchone()
    rows = c.execute("SELECT id,wallet_address,username FROM users WHERE lower(username)='orcagent' AND is_verified=1").fetchall()
    if len(rows) != 1 or (pinned and str(rows[0][0]) != pinned[0]):
        return None
    if not pinned:
        c.execute("INSERT INTO platform_assistant_settings VALUES('author_id',?)", (str(rows[0][0]),))
    return rows[0]

def utcstamp(now):
    return dt.datetime.fromtimestamp(now, dt.timezone.utc).strftime('%Y-%m-%d %H:%M:%S')

def due_slot(now):
    local = dt.datetime.fromtimestamp(now, TZ)
    for hour in reversed(HOURS):
        slot = local.replace(hour=hour,minute=0,second=0,microsecond=0)
        age = now - slot.timestamp()
        if 0 <= age < 1800:
            return slot
    return None

def publish_due(db, now=None):
    now = time.time() if now is None else now
    slot = due_slot(now)
    if slot is None:
        return None  # Skip missed slots; never flood the feed after downtime.
    with sqlite3.connect(db, timeout=8) as c:
        c.execute('BEGIN IMMEDIATE')
        if not enabled(c, 'posts'):
            return None
        author = identity(c)
        if not author:
            return None
        key = 'post:' + slot.isoformat()
        if c.execute('SELECT 1 FROM platform_assistant_events WHERE event_key=?', (key,)).fetchone():
            return None
        sequence = (slot.date() - dt.date(2026,10,4)).days * 3 + HOURS.index(slot.hour)
        topic, text = THESES[sequence % len(THESES)]
        content = 'OrcAgent · Platform thesis (automated)\n\n' + text
        cur = c.execute('INSERT INTO feed_posts(wallet,content,created_at) VALUES(?,?,?)',
                        (author[1], content, utcstamp(now)))
        post_id = 'p'+str(cur.lastrowid)
        c.execute('INSERT INTO platform_assistant_events VALUES(?,?,?,?,?,?,?)',
                  (key,'post',None,post_id,None,topic,now))
        return post_id

def within_reply_limits(c,user_id,now):
    recent = c.execute("SELECT COUNT(*) FROM platform_assistant_events WHERE kind='reply' AND source_user_id=? AND created_at>?",(user_id,now-900)).fetchone()[0]
    daily = c.execute("SELECT COUNT(*) FROM platform_assistant_events WHERE kind='reply' AND source_user_id=? AND created_at>?",(user_id,now-86400)).fetchone()[0]
    total = c.execute("SELECT COUNT(*) FROM platform_assistant_events WHERE kind='reply' AND created_at>?",(now-86400,)).fetchone()[0]
    return recent<6 and daily<20 and total<120

def reply_to_post(d,post_number,wallet,now=None):
    # Only a successfully authenticated NEW post; no edits, reposts or backfill.
    if type(post_number) is not int or post_number<=0:
        return None
    now = time.time() if now is None else now
    with sqlite3.connect(d.DB_FILE,timeout=8) as c:
        c.execute('BEGIN IMMEDIATE')
        if not enabled(c,'replies'):
            return None
        author = identity(c)
        if not author:
            return None
        post = c.execute('SELECT wallet,content FROM feed_posts WHERE id=?',(post_number,)).fetchone()
        member = c.execute('SELECT id FROM users WHERE wallet_address=?',(wallet,)).fetchone()
        if not post or post[0]!=wallet or not member or member[0]==author[0]:
            return None
        text = d._feed_text_part(post[1]) if hasattr(d,'_feed_text_part') else re.split(r'__(?:CHART|TRADE|CALL)__',post[1],maxsplit=1)[0]
        response = answer(text)
        key = 'post-reply:'+str(post_number)
        if not response or c.execute('SELECT 1 FROM platform_assistant_events WHERE event_key=?',(key,)).fetchone() or not within_reply_limits(c,member[0],now):
            return None
        topic,message = response
        post_id = 'p'+str(post_number)
        cur = c.execute('INSERT INTO feed_replies(user_id,post_id,message,created_at,parent_reply_id) VALUES(?,?,?,?,NULL)',
                        (author[0],post_id,message,utcstamp(now)))
        c.execute('INSERT INTO platform_assistant_events VALUES(?,?,?,?,?,?,?)',
                  (key,'reply',member[0],post_id,cur.lastrowid,topic,now))
        c.execute('INSERT INTO notifications(user_id,type,content,link,actor_wallet) VALUES(?,?,?,?,?)',
                  (member[0],'reply','OrcAgent answered your platform question',d._reply_link(c,post_id,cur.lastrowid),author[1]))
        return cur.lastrowid

def reply_to(d, source_id, wallet, now=None):
    now = time.time() if now is None else now
    with sqlite3.connect(d.DB_FILE, timeout=8) as c:
        c.execute('BEGIN IMMEDIATE')
        if not enabled(c, 'replies'):
            return None
        author = identity(c)
        if not author:
            return None
        source = c.execute('SELECT user_id,post_id,message,created_at,parent_reply_id FROM feed_replies WHERE id=?', (source_id,)).fetchone()
        if not source or source[0] == author[0]:
            return None
        member = c.execute('SELECT wallet_address FROM users WHERE id=?', (source[0],)).fetchone()
        if not member or member[0] != wallet or source[1][:1] not in ('p','t'):
            return None  # Home feed only; never publish private group context.
        created = d._feed_post_created_at(c, source[1])
        if not created or c.execute('SELECT datetime(?)>=datetime(?)', (source[3],created)).fetchone()[0] != 1:
            return None
        explicit = answer(source[2])
        response = explicit
        previous = None
        use_learning = enabled(c,'learning')
        if explicit and use_learning:
            previous = learning.prior(c,d,source,author[0])
            if explicit[0]=='scope':
                topic = learning.lookup(c,d,source[2],MENTION,LEARNABLE,now)
                clean = MENTION.sub('',source[2])
                if not topic and previous and previous[0] in LEARNABLE and len(clean)<=160 and learning.FOLLOWUP.search(clean) and not learning.UNSAFE.search(clean):
                    topic = previous[0]
                if topic:
                    response = topic, LABEL + LEARNABLE[topic]
        key = 'reply:' + str(source_id)
        if not response or c.execute('SELECT 1 FROM platform_assistant_events WHERE event_key=?', (key,)).fetchone():
            return None
        if not within_reply_limits(c,source[0],now):
            return None
        if use_learning:
            observed = explicit[0] if explicit[0]!='scope' or response[0]=='scope' else None
            learning.observe(c,d,source_id,source,observed,previous,MENTION,LEARNABLE,now)
        topic, message = response
        cur = c.execute('INSERT INTO feed_replies(user_id,post_id,message,created_at,parent_reply_id) VALUES(?,?,?,?,?)',
                        (author[0],source[1],message,utcstamp(now),source_id))
        c.execute('INSERT INTO platform_assistant_events VALUES(?,?,?,?,?,?,?)',
                  (key,'reply',source[0],source[1],cur.lastrowid,topic,now))
        c.execute('INSERT INTO notifications(user_id,type,content,link,actor_wallet) VALUES(?,?,?,?,?)',
                  (source[0],'reply','OrcAgent answered your platform question',d._reply_link(c,source[1],cur.lastrowid),author[1]))
        return cur.lastrowid

def install(d):
    app = d.app
    if getattr(app, '_orca_platform_assistant', False):
        return
    initialize(d.DB_FILE)
    app._orca_platform_assistant = True

    @app.after_request
    def mentioned(response):
        if request.path not in ('/api/feed/reply','/api/feed/post') or request.method != 'POST' or response.status_code != 200 or not response.is_json:
            return response
        data = response.get_json(silent=True)
        if not isinstance(data,dict) or not data.get('ok') or type(data.get('id')) is not int:
            return response
        try:
            wallet = d._authenticated_wallet()
            if wallet:
                reply_id = reply_to_post(d,data['id'],wallet) if request.path=='/api/feed/post' else reply_to(d,data['id'],wallet)
                if reply_id:
                    data['platform_reply_id'] = reply_id
                    response.set_data(app.json.dumps(data))
        except Exception:
            # A bot failure must never turn a successfully saved user reply into an error.
            app.logger.exception('platform assistant reply failed')
        return response

    @app.route('/admin/platform-assistant')
    def settings():
        err = d._require_role('admin','executive')
        if err:
            return err
        with sqlite3.connect(d.DB_FILE,timeout=8) as c:
            author = identity(c)
            state = dict(posts=enabled(c,'posts'),replies=enabled(c,'replies'),learning=enabled(c,'learning'),author=author[2] if author else None)
            questions = learning.dashboard(c,d,MENTION,LEARNABLE,time.time())
            recent = c.execute('SELECT kind,post_id,reply_id,topic,created_at FROM platform_assistant_events ORDER BY created_at DESC LIMIT 20').fetchall()
        return d._render_no_cache('platform_assistant_admin.html',state=state,recent=recent,theses=THESES,questions=questions,topics=LEARNABLE,csrf_token=d._get_csrf_token())

    @app.route('/api/admin/platform-assistant',methods=['POST'])
    def configure():
        err = d._require_role('admin','executive')
        if err:
            return err
        if not d._validate_csrf(request.headers.get('X-CSRF-Token','')):
            return jsonify(ok=False,error='CSRF validation failed'),403
        body = request.get_json(silent=True)
        if not isinstance(body,dict) or set(body)-{'posts','replies','learning'} or not body or any(type(v) is not bool for v in body.values()):
            return jsonify(ok=False,error='Use boolean posts/replies/learning settings'),400
        with sqlite3.connect(d.DB_FILE,timeout=8) as c:
            c.execute('BEGIN IMMEDIATE')
            for key, value in body.items():
                c.execute('INSERT OR REPLACE INTO platform_assistant_settings VALUES(?,?)',(key,'1' if value else '0'))
        return jsonify(ok=True)

    @app.route('/api/admin/platform-assistant/learning',methods=['POST'])
    def review_learning():
        err = d._require_role('admin','executive')
        if err:
            return err
        if not d._validate_csrf(request.headers.get('X-CSRF-Token','')):
            return jsonify(ok=False,error='CSRF validation failed'),403
        body = request.get_json(silent=True)
        if not isinstance(body,dict) or set(body)-{'question','topic','status'} or any(not isinstance(v,str) for v in body.values()):
            return jsonify(ok=False,error='Invalid review'),400
        wallet = d._authenticated_wallet()
        if not wallet:
            return jsonify(ok=False,error='Authentication required'),401
        try:
            with sqlite3.connect(d.DB_FILE,timeout=8) as c:
                c.execute('BEGIN IMMEDIATE')
                learning.review(c,body.get('question'),body.get('topic'),body.get('status'),wallet,time.time(),LEARNABLE)
        except ValueError as e:
            return jsonify(ok=False,error=str(e)),400
        except LookupError as e:
            return jsonify(ok=False,error=str(e)),404
        return jsonify(ok=True)

    def loop():
        while True:
            try:
                publish_due(d.DB_FILE)
            except Exception:
                app.logger.exception('platform thesis publication failed')
            time.sleep(30)
    threading.Thread(target=loop,name='orca-platform-theses',daemon=True).start()
