"""First-party platform posts and explicit @orcagent comment replies.

Deterministic rules own actions, live data, privacy and safety. An optional
sanitized AI reasoning fallback can refine complex public questions; it never
receives account-specific data or wallet secrets. SQLite publication receipts
coordinate all workers and survive restarts.
"""
from __future__ import annotations
import datetime as dt
import os
import re
import sqlite3
import threading
import time
import platform_learning as learning
import platform_live_posts as live_posts
import agent_post_images
from platform_answers import specific, trade_action_slots, merge_trade_action_slots
import platform_prices as prices
import platform_public_data as public_data
import platform_reasoner as reasoner
import orcagent_chat as chat
import orcagent_brain as brain
from zoneinfo import ZoneInfo
from flask import jsonify, request

TZ = ZoneInfo('Europe/Amsterdam')
# One platform post every 30 minutes, around the clock (Amsterdam time).
SLOT_MINUTES = 30
# A slot is published only within this many seconds of its start; a slot
# missed during downtime is skipped rather than posted late.
SLOT_WINDOW = 600
MENTION = re.compile(r'(?<![\w@])@orcagent(?![\w])', re.I)
LABEL = ''
# Approved product copy, not generated claims about prices or user performance.
THESES = (
('calls', 'A token ticker is only the start. A useful call explains the reasoning and records an entry price. Publish your analysis on OrcAgent so others can explore the call and its chart before making their own decision.'),
('community', 'Your trading circle should be your choice. Follow traders whose reasoning interests you, read their calls and ask questions. OrcAgent connects the conversation with the tools to explore a Solana token.'),
('sharing', 'Give your next trading idea some context. Share an OrcAgent call card with its author, recorded entry and a link to the full analysis. The recipient can explore the call and chart in the app.'),
('portfolio', 'A new idea belongs in the context of what you already hold. Use your portfolio alongside the calls and Solana charts you explore on OrcAgent. The decision to trade remains yours.'),
('feedback', 'OrcAgent is growing with its community. If a screen or action gets in your way, tag @orcagent with the feature and what happened. The automated assistant can explain platform functions; account-specific issues need human support.'),
('wallet', 'Connect Phantom to explore OrcAgent with your wallet. Never share your recovery phrase or private key in a post, comment or DM. The platform assistant will never ask for those secrets.'),
('entry', 'A recorded entry gives a call a reference point. It is not a guaranteed execution price or a promise of returns. Read the analysis, explore the chart and make your own decision.'),
('discussion', 'Good questions make a trading community more useful. Ask what someone is watching and why. OrcAgent puts profiles, calls, replies and DMs beside the tools to explore Solana tokens.'),
('referrals', 'Invite people who want to explore the community. OrcAgent referrals share 20% of the trading fees generated by attributed users, subject to the referral rules. That is a share of the fee, not their trading volume.'),
('charts', 'A call is a starting point to investigate. Open its analysis, inspect the token and explore the chart. OrcAgent gives the idea a path to the trading tools; you decide whether to take a trade.'),
('transparency', 'A useful call has an author, reasoning and a recorded entry. Keep those details together when you share it. OrcAgent call cards link back to the full call so the context stays within reach.'),
('follow', 'Build a feed around people whose thinking you want to understand. Follow traders, compare their analyses and continue the conversation in comments or DMs. Explore OrcAgent at your own pace.'),
('costs', 'Review the amount and costs before confirming a trade. Users fund their own transaction costs on OrcAgent. A community call is an opinion, not an instruction to buy.'),
('learning', 'Ask about the reasoning behind an idea. A chart and a call can help you investigate, but no post can guarantee an outcome. OrcAgent connects the tools and conversation so you can decide for yourself.'),
('onboarding', 'New here? Connect Phantom, explore the feed and open a call that interests you. Read the analysis and chart, then follow the traders you want to hear from. Welcome to OrcAgent.'),
('save', 'Tap Share call on a call for a link and a downloadable card. Use Copy link, Share on X or Save card from the share window. New accounts that join through your link count as your referrals.'),
('support', 'Have a question about OrcAgent? Tag @orcagent in a comment and name the feature. The automated assistant answers platform questions and asks for detail when it cannot identify the issue.'),
('portfolio_context', 'Trading tools become more useful with context. Explore community calls and Solana charts, then consider a new idea against your current holdings. OrcAgent brings those steps into the same app.'),
('feedback_loop', 'The people using OrcAgent see where it can improve. Tag @orcagent with the page you used, the action you tried and what appeared on screen. Useful feedback helps us find the next thing to fix.'),
('share_context', 'A shared ticker should have a way back to the original analysis. OrcAgent call links open the specific call and its chart. Share an idea with the reasoning behind it.'),
('independent', 'Follow an idea without giving up your own judgement. Read the call, explore the chart and consider the costs. OrcAgent provides tools and conversations; you make the trading decision.'),
('social', 'Community is more than a list of tickers. Profiles, follows, comments and DMs help you understand the people behind an idea. Explore the Solana trading community on OrcAgent.'),
('recorded', 'Recorded entry prices preserve the reference point of a call. They do not change into a promise about future performance. Put your analysis alongside that reference when you publish a call.'),
('fees_not_volume', 'Reward percentages on OrcAgent refer to collected platform fees. They are not percentages of the full trade amount. Read the referral rules to understand what qualifies.'),
('live_market', 'Live Market lists Solana tokens with prices that refresh every second. Open a token to see its chart, liquidity and recent activity before you decide anything. Explore it at your own pace.'),
('stop_loss', 'A stop loss and take profit can be set when you buy on Live Market. They are checked continuously and sell automatically when reached. Choose levels that fit your own risk; they cannot guarantee a price.'),
('bot', 'The Auto Trading Bot follows the settings you choose, including your stop loss and take profit. It trades from your own trading wallet and you can stop it at any time. Review its settings before you start it.'),
('live_trades', 'Live Trades shows buys and sells on OrcAgent as they happen, with entry and exit. Use it to see what the community is doing, then do your own research before following any trade.'),
('tips', 'Liked someone\'s analysis? Use the Tip button on their profile to send them a tip as a thank-you.'),
('dm_reactions', 'Long-press a message in your DMs to react with an emoji. A quick reaction keeps a conversation going without another message.'),
('notifications', 'Turn on notifications so you know when someone replies, follows you or sends a DM. You can switch push messages off again in Settings whenever you like.'),
('groups', 'Groups bring traders with a shared interest into one conversation. Join a group and discuss ideas with people who watch the same tokens.'),
('leaderboard', 'The leaderboard shows which traders are doing well on OrcAgent. Open a profile to read their calls and reasoning. Past results never guarantee future returns.'),
('images', 'Add a picture to your post to show the chart or setup you are talking about. A screenshot with your reasoning says more than a ticker alone.'),
('withdraw', 'Your Portfolio shows what you hold. You can withdraw a token to another wallet; the balance is checked on-chain before anything is sent.'),
('light_mode', 'Prefer a lighter screen? Switch on Light mode from the menu or in Settings. OrcAgent remembers your choice on each device.'),
('calls_tab', 'The Calls tab in the feed gathers the latest calls in one place. Open one to see who made it, the recorded entry and how the token has moved since.'),
('watchlist', 'On Live Market, add tokens you are interested in to your watchlist. Come back to them when you are ready to take a closer look.'),
('pwa', 'Add OrcAgent to your home screen for an app-like experience: faster to open and with push notifications. Use Share and then Add to Home Screen in your browser.'),
('replies', 'Reply to a post to ask about the reasoning or add your own view. Good conversations under a call help everyone understand the idea better.'),
('reposts', 'Found a call worth sharing with your followers? Repost it. The original author keeps the credit and your followers see it in their feed.'),
('profile', 'Your profile is where others get to know you as a trader. Add a picture and a username so people recognise your calls and replies in the feed.'),
('risk', 'Memecoins move fast in both directions. Only trade with money you can afford to lose, and use a stop loss if that suits your plan. OrcAgent gives you the tools; the decision is always yours.'),
('bullish_bearish', 'See a trending token in the feed? Vote Bullish or Bearish on it to show how you read the move, and see how others voted.'),
('search', 'Looking for something specific? Use the search at the top to find a token, an address or a trader on OrcAgent.'),
('top_traders', 'Live Market shows the top traders of the last 24 hours. Open a profile to see who they are and what they trade.'),
('market_pulse', 'Market pulse on Live Market shows the trades of the last 24 hours, how many traders are online and how many tokens are tracked.'),
('safety_filters', 'Live Market filters can show only tokens with LP locked or mint revoked, hide honeypots, require verified socials and set a minimum liquidity. Filters help, but they never make a token safe.'),
('sort_market', 'Sort Live Market by Trending, Top gainers, New pairs, Volume leaders or Friends buying to look at the market from a different angle.'),
('dm_images', 'Explaining a setup in DMs? Send a picture of the chart along with your message so the other person sees what you mean.'),
('edit_post', 'Spotted a typo after posting? Open the menu on your own post and choose Edit to fix it.'),
('feed_filters', 'At the top of the feed, switch between For You, Following and Calls. Each view shows a different side of the community.'),
)

# Product texts OrcAgent used to post that were not true: video posts, an
# invitations dashboard, token cards in DMs, calls in groups, the wallet
# approving each tip, Token Launch. Posts it already published with exactly
# one of these texts are removed once, at start-up.
RETIRED = (
    'A useful invitation starts with an idea worth discussing. Share a personal call link and track the new accounts and qualifying trades it brings in. Your invitation totals are private.',
    'Your shared calls can be explored by others. Your invitation dashboard totals are private. OrcAgent keeps the public idea and your personal tracking in their respective places.',
    'Share a call with your personal invitation link to track the people it brings in. Existing accounts and self-invitations do not count as new accounts. Check Invitations for the rules and your private totals.',
    'Liked someone\'s analysis? You can tip them from their profile. Your wallet approves every tip, and the amount goes straight to the person you chose.',
    'Discussing a token in DMs? Share it as a token card so the chart and details travel with the conversation. Keep wallet secrets out of every message.',
    'Groups bring traders with a shared interest into one conversation. Join a group, share calls and discuss ideas with people who watch the same tokens.',
    'Posts can include a short video of up to 30 seconds. Show a chart walkthrough or explain your idea in your own words, right in the feed.',
    'Thinking of launching a Solana token? Token Launch walks you through it step by step, and you approve the launch in your own wallet. Read every step before you confirm.',
)

# English platform guidance; both English and Dutch keywords are understood.
FAQ = (
    ('secrets', 'seed|recovery phrase|private key|secret key|herstelzin|priv[eé]sleutel', 'Never post your recovery phrase or private key. Describe your wallet issue without credentials; OrcAgent will never ask for those secrets.'),
    ('bug', 'not working|doesn.t work|error|bug|failed|stuck|werkt niet|fout|mislukt|vast|probleem', 'Which OrcAgent page and action failed? Share the error and your device type so the team can review it. Keep wallet secrets private.'),
    ('creator', 'creator|creators|reward|beloning|verdien|paid|betaald|payout|uitbetaling', 'The separate call-based Creator Rewards page is no longer part of OrcAgent. Token-launch creator fees, when available, are managed from Token Launch: https://orcagent.fun/token-launch.'),
    ('referral', 'referral|referrer|invite|invitation|uitnodig|doorverwijs', 'Referrals share 20% of fees from attributed users, not trade volume. Copy your personal link here: https://orcagent.fun/referrals. Would you like help sharing it?'),
    ('fees', r'\bfees?\b|cost|kost|kosten|percentage|procent|%', 'Reward percentages apply to collected platform fees, not trading volume. You fund transaction costs. Review the costs before confirming; I cannot calculate a personal quote.'),
    ('share', r'\bshare\b|sharing|deel|delen|card|kaart', 'Open a call and tap Share call to copy its link or save its card. The shared link opens that exact call. Are you sharing a link or a card?'),
    ('calls', r'\bcalls?\b|analysis|analyse|entry|instap', 'A call records analysis and an entry reference, not a guaranteed return. Explore a call in the feed: https://orcagent.fun/#app-home. Would you like help reading or publishing one?'),
    ('wallet', 'phantom|connect|login|log.?in|wallet|verbinden|inloggen', 'Tap Connect wallet and approve in Phantom. Return to your chosen browser or PWA. If it fails, share the screen and error, never your recovery phrase.'),
    ('portfolio', 'portfolio|holding|balance|saldo|bezitting', 'Check holdings and activity in Portfolio: https://orcagent.fun/#app-portfolio. Missing something? Tell me which asset and what you see; I cannot access your account.'),
    ('trading', 'trad|buy|sell|swap|kopen|verkopen|ruil|chart|grafiek|solana|chain', 'Open Live Market: https://orcagent.fun/live-market. Choose a token, tap Buy or Sell, enter an amount and review the costs. Which token would you like to explore?'),
    ('community', r'follow|volg|\bdm\b|message|bericht|community|feed|comment|reage', 'Follow traders from their profiles, discuss calls in comments or chat in DMs. Tag @orcagent for help with platform features.'),
)

LEARNABLE = {topic:english for topic,pattern,english in FAQ if topic not in ('secrets','bug')}
LEARNABLE.update({
    'trade_action': (
        'I can help set up a buy or sell, but your wallet must approve it. '
        'For a buy, tell me the token and SOL amount so I can keep the next step specific.'
    ),
    'transfer_action': (
        'I can help set up a USDC send or tip, but your wallet must approve it. '
        'Tell me the recipient and amount so I can keep the next step specific.'
    ),
})

def answer(message, context=None, market=None, public=None, action_state=None):
    if not isinstance(message, str) or not MENTION.search(message):
        return None
    raw = MENTION.sub('', message)
    clean = raw.lower()
    public_query = public_data.query(raw)
    # Privacy is evaluated before price/token parsing. "Show my SOL balance"
    # must never turn into a public SOL-price answer or expose account data.
    if public_query and public_query.get('kind') == 'private':
        return public_data.render(public_query, public)
    price_query = prices.query(raw)
    if price_query:
        return prices.render(price_query, market)
    if public_query:
        live_answer = public_data.render(public_query, public)
        if live_answer:
            return live_answer
    targeted = specific(clean, context, action_state)
    if targeted:
        return targeted
    token = re.fullmatch(r'\s*(?:do you know\s+|tell me about\s+|what is\s+)?\$?([a-z][a-z0-9_]{1,19})\s+token[\s?!.]*',clean)
    if token:
        symbol = token[1].upper()
        return 'token_choice', LABEL + f"Do you mean ${symbol}? Choose the matching token below, then tell me which OrcAgent feature you want help with."
    for topic, pattern, english in FAQ:
        if re.search(pattern, clean, re.I):
            return topic, LABEL + english
    if re.search(r'benefits?|what (?:can|does)|features?|voordelen|mogelijkheden',clean):
        return 'overview', LABEL + 'OrcAgent brings Solana charts, trading, calls and community into one app. Follow traders, share your analysis and track holdings in Portfolio.'
    if re.fullmatch(r'\s*(?:(?:hi|hello|hey)[\s,!]+)?(?:how are you(?: doing)?|how.s it going|hoe gaat het)[\s!?.,]*',clean):
        return 'welcome', LABEL + "I'm doing well, thanks! How about you? What can I help you with on OrcAgent today?"
    if re.fullmatch(r'\s*(?:hi|hello|hey|hello there|hallo|hoi)[\s!?.,]*',clean):
        return 'welcome', LABEL + "Hey! Welcome to OrcAgent. What would you like to explore today: calls, charts or your portfolio?"
    if re.fullmatch(r"\s*(?:i.m (?:good|fine|well)|good|fine|doing well|thanks|thank you|goed|dank je)(?:[\s,!]+(?:thanks|thank you))?[\s!?.,]*",clean):
        return 'welcome', LABEL + "Thanks for sharing! What would you like to do on OrcAgent today? Explore the feed: https://orcagent.fun/#app-home"
    return 'scope', LABEL + 'Happy to help! Which OrcAgent feature is your question about, and what are you trying to do? Tell me the screen or action so I can give specific steps.'

def initialize(db):
    with sqlite3.connect(db, timeout=8) as c:
        learning.initialize(c)
        c.execute("CREATE TABLE IF NOT EXISTS platform_assistant_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL)")
        c.execute("""CREATE TABLE IF NOT EXISTS platform_assistant_events (
            event_key TEXT PRIMARY KEY,kind TEXT NOT NULL,source_user_id INTEGER,
            post_id TEXT,reply_id INTEGER,topic TEXT NOT NULL,created_at REAL NOT NULL)""")
        c.execute('CREATE INDEX IF NOT EXISTS platform_assistant_limits ON platform_assistant_events(kind,source_user_id,created_at)')
        _clean_existing_prefixes(c)
        _remove_retired_posts(c)

def _clean_existing_prefixes(c):
    """Remove only fixed intros from recorded posts/replies of the verified agent."""
    if not c.in_transaction:
        c.execute('BEGIN IMMEDIATE')
    key = 'content_prefix_cleanup_v1'
    if c.execute('SELECT 1 FROM platform_assistant_settings WHERE key=?', (key,)).fetchone():
        return
    author = identity(c)
    if not author:
        return
    prefix = 'OrcAgent · Platform thesis (automated)'
    posts = c.execute("SELECT p.id,p.content FROM feed_posts p JOIN platform_assistant_events e "
                      "ON e.post_id='p'||p.id AND e.kind='post' WHERE p.wallet=?", (author[1],)).fetchall()
    for post_id, content in posts:
        if isinstance(content, str) and content.startswith(prefix):
            c.execute('UPDATE feed_posts SET content=? WHERE id=? AND content=?',
                      (content[len(prefix):].lstrip(), post_id, content))
    prefix = 'Automated · '
    replies = c.execute("SELECT r.id,r.message FROM feed_replies r JOIN platform_assistant_events e "
                        "ON e.reply_id=r.id AND e.kind='reply' WHERE r.user_id=?", (author[0],)).fetchall()
    for reply_id, message in replies:
        if isinstance(message, str) and message.startswith(prefix):
            c.execute('UPDATE feed_replies SET message=? WHERE id=? AND message=?',
                      (message[len(prefix):].lstrip(), reply_id, message))
    c.execute('INSERT OR IGNORE INTO platform_assistant_settings VALUES(?,?)', (key, '1'))


def _remove_retired_posts(c):
    """Once: delete the posts OrcAgent itself published with a RETIRED text,
    with their replies, likes, reposts and notifications. Only posts recorded
    as published by this assistant, from the official account, are touched."""
    key = 'retired_posts_cleanup_v1'
    if c.execute('SELECT 1 FROM platform_assistant_settings WHERE key=?', (key,)).fetchone():
        return 0
    author = identity(c)
    if not author:
        return 0   # no official account yet; try again next start
    marks = ','.join('?' * len(RETIRED))
    ids = [r[0] for r in c.execute(
        "SELECT p.id FROM feed_posts p JOIN platform_assistant_events e ON e.post_id='p'||p.id AND e.kind='post' "
        "WHERE p.wallet=? AND p.content IN (%s)" % marks, (author[1],) + tuple(RETIRED))]
    for post_id in ids:
        pid, link = 'p%d' % post_id, '/#post-p%d' % post_id
        for sql, args in (
                ('DELETE FROM feed_reply_likes WHERE reply_id IN (SELECT id FROM feed_replies WHERE post_id=?)', (pid,)),
                ('DELETE FROM feed_replies WHERE post_id=?', (pid,)),
                ('DELETE FROM post_likes WHERE post_id=?', (pid,)),
                ('DELETE FROM post_reactions WHERE post_id=?', (pid,)),
                ('DELETE FROM feed_reposts WHERE post_id=?', (pid,)),
                ('DELETE FROM notifications WHERE link=? OR link LIKE ?', (link, link + '-reply-%'))):
            try:
                c.execute(sql, args)
            except sqlite3.OperationalError:
                pass   # a table this database does not have
        c.execute('DELETE FROM feed_posts WHERE id=?', (post_id,))
    c.execute('INSERT OR IGNORE INTO platform_assistant_settings VALUES(?,?)', (key, str(len(ids))))
    if ids:
        print('[platform-assistant] removed %d earlier post(s) with an untrue product text' % len(ids), flush=True)
    return len(ids)


def enabled(c, key):
    env = {'posts':'ORCAGENT_PLATFORM_POSTS','replies':'ORCAGENT_PLATFORM_REPLIES','learning':'ORCAGENT_PLATFORM_LEARNING'}[key]
    if os.environ.get(env, '1') == '0':
        return False
    row = c.execute('SELECT value FROM platform_assistant_settings WHERE key=?', (key,)).fetchone()
    return not row or row[0] == '1'

def identity(c):
    pinned = c.execute("SELECT value FROM platform_assistant_settings WHERE key='author_id'").fetchone()
    rows = c.execute("SELECT id,wallet_address,username FROM users WHERE lower(username)='orcagent' AND is_verified=1").fetchall()
    if len(rows) != 1 or (pinned and str(rows[0][0]) != pinned[0]):
        return None
    if not pinned:
        c.execute("INSERT INTO platform_assistant_settings VALUES('author_id',?)", (str(rows[0][0]),))
    return rows[0]

def utcstamp(now):
    return dt.datetime.fromtimestamp(now, dt.timezone.utc).strftime('%Y-%m-%d %H:%M:%S')

def due_slot(now):
    local = dt.datetime.fromtimestamp(now, TZ)
    slot = local.replace(minute=local.minute - local.minute % SLOT_MINUTES, second=0, microsecond=0)
    if 0 <= now - slot.timestamp() < SLOT_WINDOW:
        return slot
    return None

def slot_index(slot):
    """Position of this slot within its day: 0 at 00:00 ... 47 at 23:30."""
    return (slot.hour * 60 + slot.minute) // SLOT_MINUTES

def _opening(text):
    """The first three words: how a post opens."""
    return ' '.join(str(text or '').split()[:3]).lower()

def publish_due(db, now=None, live_data=None, render=None):
    """Publish this slot's post, if it is due and not yet published.

    live_data(), when given, returns (trending tokens, SOL price in USD). The
    post is then the best current live post about calls or trending tokens
    (platform_live_posts); render(picture spec, seed), when given, draws its
    picture (agent_post_images) and returns the image URL. Both happen before
    the write transaction, so slow logo or price sources never hold the
    database lock. A post whose picture could not be drawn carries the live
    call or chart card instead. Only when nothing is live does a product text
    go out. OrcAgent never posts a text it has posted before: if every option
    was already used, the slot is skipped.
    """
    now = time.time() if now is None else now
    slot = due_slot(now)
    if slot is None:
        return None  # Skip missed slots; never flood the feed after downtime.
    key = 'post:' + slot.isoformat()

    def fresh(c, wallet, text):
        return not c.execute('SELECT 1 FROM feed_posts WHERE wallet=? AND content=?', (wallet, text)).fetchone()

    picked = None   # (topic, content, image_url)
    if live_data is not None:
        with sqlite3.connect(db, timeout=8) as c:
            if c.execute('SELECT 1 FROM platform_assistant_events WHERE event_key=?', (key,)).fetchone():
                return None
            if not enabled(c, 'posts'):
                return None
            author = identity(c)
            if not author:
                return None
        try:
            tokens, sol_usd = live_data()
        except Exception:
            tokens, sol_usd = [], 0.0
        choice = None
        with sqlite3.connect(db, timeout=8) as c:
            last = c.execute('SELECT content FROM feed_posts WHERE wallet=? ORDER BY id DESC LIMIT 1',
                             (author[1],)).fetchone()
            opening = _opening(last[0]) if last else ''
            for topic, texts, media, embed in live_posts.candidates(c, now, slot_index(slot), tokens, sol_usd):
                usable = [t for t in texts if fresh(c, author[1], t) and fresh(c, author[1], t + embed)]
                # Never open the way the previous post did.
                text = next((t for t in usable if _opening(t) != opening), None) or (usable[0] if usable else None)
                if text:
                    choice = (topic, text, media, embed)
                    break
            variant = 0
            if choice and choice[2]:
                prefixes = ('trending:',) if choice[2]['kind'] == 'trending' else ('call:', 'milestone:', 'best:')
                variant = sum(c.execute("SELECT COUNT(*) FROM platform_assistant_events WHERE kind='post' AND topic LIKE ?",
                                        (p_ + '%',)).fetchone()[0] for p_ in prefixes)
        if choice:
            topic, text, media, embed = choice
            image_url = None
            if media and render is not None:
                try:
                    image_url = render(media, topic + '|' + slot.isoformat(), variant)
                except Exception:
                    image_url = None
            picked = (topic, text if image_url else text + embed, image_url)

    with sqlite3.connect(db, timeout=8) as c:
        c.execute('BEGIN IMMEDIATE')
        if not enabled(c, 'posts'):
            return None
        author = identity(c)
        if not author:
            return None
        if c.execute('SELECT 1 FROM platform_assistant_events WHERE event_key=?', (key,)).fetchone():
            return None
        if picked is not None and not fresh(c, author[1], picked[1]):
            picked = None
        if picked is None:
            # A product text, in the daily rotation order, that OrcAgent has
            # never posted before.
            sequence = (slot.date() - dt.date(2026,10,4)).days * (24 * 60 // SLOT_MINUTES) + slot_index(slot)
            for i in range(len(THESES)):
                topic, text = THESES[(sequence + i) % len(THESES)]
                if fresh(c, author[1], text):
                    picked = (topic, text, None)
                    break
        if picked is None:
            return None
        topic, content, image_url = picked
        if image_url:
            cur = c.execute('INSERT INTO feed_posts(wallet,content,created_at,image_url) VALUES(?,?,?,?)',
                            (author[1], content, utcstamp(now), image_url))
        else:
            cur = c.execute('INSERT INTO feed_posts(wallet,content,created_at) VALUES(?,?,?)',
                            (author[1], content, utcstamp(now)))
        post_id = 'p'+str(cur.lastrowid)
        c.execute('INSERT INTO platform_assistant_events VALUES(?,?,?,?,?,?,?)',
                  (key,'post',None,post_id,None,topic,now))
        return post_id

def within_reply_limits(c,user_id,now):
    # User-requested unlimited platform conversations; provider quotas remain
    # separate and only affect price lookups, never the ability to reply.
    return True

def _conversation_message(c,d,source,author_id,now):
    message = source[2]
    if MENTION.search(message):
        return message
    previous = learning.prior(c,d,source,author_id)
    if previous and source[4]:
        parent = c.execute('SELECT user_id FROM feed_replies WHERE id=?',(source[4],)).fetchone()
        if parent and parent[0]==author_id:
            # The authenticated conversation stays open until the user leaves it.
            # prior() still verifies the source user, thread and official event.
            return '@orcagent '+message
    return message


def _trade_thread_state(c,d,source,author_id):
    """Recover trade slots only from this authenticated user + OrcAgent reply chain."""
    user_id, post_id = source[0], source[1]
    current = source
    current_id = None
    messages = []
    visited = set()
    for _ in range(12):
        if not current or current[1] != post_id or current[0] not in (user_id, author_id):
            break
        if current[0] == user_id:
            messages.append(current[2])
        else:
            if current_id is None:
                break
            event = c.execute(
                "SELECT topic FROM platform_assistant_events "
                "WHERE kind='reply' AND reply_id=? AND source_user_id=?",
                (current_id, user_id),
            ).fetchone()
            if not event or event[0] != 'trade_action':
                break
        parent = current[4]
        if not parent or parent in visited:
            if current[0] == author_id and not parent and post_id.startswith('p'):
                post = c.execute(
                    'SELECT p.content FROM feed_posts p JOIN users u ON u.wallet_address=p.wallet '
                    'WHERE p.id=? AND u.id=?',
                    (post_id[1:], user_id),
                ).fetchone()
                if post:
                    text = d._feed_text_part(post[0]) if hasattr(d,'_feed_text_part') else re.split(
                        r'__(?:CHART|TRADE|CALL)__',post[0],maxsplit=1
                    )[0]
                    messages.append(text)
            break
        visited.add(parent)
        current_id = parent
        current = c.execute(
            'SELECT user_id,post_id,message,created_at,parent_reply_id FROM feed_replies WHERE id=?',
            (parent,),
        ).fetchone()
    state = None
    for item in reversed(messages):
        slots = trade_action_slots(MENTION.sub('', item))
        if any(value is not None for value in slots.values()):
            state = merge_trade_action_slots(state, slots)
    return state

def _prepare_market(d, source_id, wallet, kind, now):
    # External I/O finishes BEFORE BEGIN IMMEDIATE. Revalidate the source below.
    with sqlite3.connect(d.DB_FILE, timeout=2) as c:
        if not enabled(c, 'replies'):
            return None
        if kind == 'post':
            row = c.execute('SELECT p.content,u.id FROM feed_posts p JOIN users u ON u.wallet_address=p.wallet WHERE p.id=? AND p.wallet=?',
                            (source_id,wallet)).fetchone()
        else:
            row = c.execute("SELECT r.message,r.user_id FROM feed_replies r JOIN users u ON u.id=r.user_id WHERE r.id=? AND u.wallet_address=? AND substr(r.post_id,1,1) IN ('p','t')",
                            (source_id,wallet)).fetchone()
        if not row or not within_reply_limits(c,row[1],now):
            return None
        text = d._feed_text_part(row[0]) if kind=='post' and hasattr(d,'_feed_text_part') else re.split(r'__(?:CHART|TRADE|CALL)__',row[0],maxsplit=1)[0]
        if kind=='reply' and not MENTION.search(text):
            source = c.execute('SELECT user_id,post_id,message,created_at,parent_reply_id FROM feed_replies WHERE id=?',(source_id,)).fetchone()
            official = c.execute("SELECT id FROM users WHERE lower(username)='orcagent' AND is_verified=1").fetchall()
            if source and len(official)==1:
                text = _conversation_message(c,d,source,official[0][0],now)
        if not MENTION.search(text):
            return None
        q = prices.query(MENTION.sub('',text))
    if not q or q['kind'] not in ('major','token','search'):
        return None
    return text, prices.fetch(q,dex_get=getattr(d,'_dex_get',None))

def _market_for(text, prepared):
    return prepared[1] if prepared and prepared[0]==text else None

def _prepare_public(d, source_id, wallet, kind, now):
    # Public-data lookup happens before the write transaction. The data module
    # itself is allowlisted and never reads account-specific/private tables.
    with sqlite3.connect(d.DB_FILE, timeout=2) as c:
        if not enabled(c, 'replies'):
            return None
        if kind == 'post':
            row = c.execute('SELECT p.content,u.id FROM feed_posts p JOIN users u ON u.wallet_address=p.wallet WHERE p.id=? AND p.wallet=?',
                            (source_id,wallet)).fetchone()
        else:
            row = c.execute("SELECT r.message,r.user_id FROM feed_replies r JOIN users u ON u.id=r.user_id WHERE r.id=? AND u.wallet_address=? AND substr(r.post_id,1,1) IN ('p','t')",
                            (source_id,wallet)).fetchone()
        if not row or not within_reply_limits(c,row[1],now):
            return None
        text = d._feed_text_part(row[0]) if kind=='post' and hasattr(d,'_feed_text_part') else re.split(r'__(?:CHART|TRADE|CALL)__',row[0],maxsplit=1)[0]
        if kind=='reply' and not MENTION.search(text):
            source = c.execute('SELECT user_id,post_id,message,created_at,parent_reply_id FROM feed_replies WHERE id=?',(source_id,)).fetchone()
            official = c.execute("SELECT id FROM users WHERE lower(username)='orcagent' AND is_verified=1").fetchall()
            if source and len(official)==1:
                text = _conversation_message(c,d,source,official[0][0],now)
        if not MENTION.search(text):
            return None
        q = public_data.query(MENTION.sub('',text))
    if not q:
        return None
    return text, public_data.fetch(q,d)

def _public_for(text, prepared):
    return prepared[1] if prepared and prepared[0]==text else None

def _prepare_reasoning(d, source_id, wallet, kind, now):
    """Do optional external reasoning before the write transaction.

    Only a sanitized public feed question and reviewed facts leave the process.
    No account/private tables are read into the model prompt.
    """
    with sqlite3.connect(d.DB_FILE, timeout=2) as c:
        if not enabled(c, 'replies'):
            return None
        author = identity(c)
        if not author:
            return None
        context_topic = None
        action_state = None
        if kind == 'post':
            row = c.execute(
                'SELECT p.content,u.id FROM feed_posts p JOIN users u ON u.wallet_address=p.wallet '
                'WHERE p.id=? AND p.wallet=?',
                (source_id,wallet),
            ).fetchone()
            if not row or row[1] == author[0]:
                return None
            text = d._feed_text_part(row[0]) if hasattr(d,'_feed_text_part') else re.split(
                r'__(?:CHART|TRADE|CALL)__',row[0],maxsplit=1
            )[0]
        else:
            source = c.execute(
                'SELECT user_id,post_id,message,created_at,parent_reply_id FROM feed_replies WHERE id=?',
                (source_id,),
            ).fetchone()
            if not source or source[0] == author[0] or source[1][:1] not in ('p','t'):
                return None
            member = c.execute('SELECT wallet_address FROM users WHERE id=?',(source[0],)).fetchone()
            if not member or member[0] != wallet:
                return None
            text = _conversation_message(c,d,source,author[0],now)
            previous = learning.prior(c,d,source,author[0])
            context_topic = previous[0] if previous else None
            action_state = _trade_thread_state(c,d,source,author[0]) if context_topic == 'trade_action' else None
        if not MENTION.search(text):
            return None
        raw = MENTION.sub('',text).strip()
        # Never send live-data questions to the reasoning provider. Their
        # deterministic data modules are authoritative and privacy-scoped.
        if prices.query(raw) or public_data.query(raw):
            return None
        deterministic = answer(text, context_topic, action_state=action_state)
    smart = reasoner.reason(d, raw, context_topic, deterministic)
    return (text, smart) if smart else None


def _reasoning_for(text, prepared):
    return prepared[1] if prepared and prepared[0] == text else None

def _chat_source(d, source_id, wallet, kind, now):
    """Public inputs for a conversational (Grok-style) reply, or None when a
    deterministic module owns the answer. No network; reads only public
    Home-feed text and usernames (orcagent_chat.thread_context)."""
    with sqlite3.connect(d.DB_FILE, timeout=2) as c:
        if not enabled(c, 'replies'):
            return None
        author = identity(c)
        if not author:
            return None
        context_topic = None
        action_state = None
        thread = []
        if kind == 'post':
            row = c.execute(
                'SELECT p.content,u.id,u.username FROM feed_posts p JOIN users u ON u.wallet_address=p.wallet '
                'WHERE p.id=? AND p.wallet=?',
                (source_id, wallet),
            ).fetchone()
            if not row or row[1] == author[0]:
                return None
            text = d._feed_text_part(row[0]) if hasattr(d, '_feed_text_part') else re.split(
                r'__(?:CHART|TRADE|CALL)__', row[0], maxsplit=1)[0]
            user_id, asker = row[1], row[2]
        else:
            source = c.execute(
                'SELECT user_id,post_id,message,created_at,parent_reply_id FROM feed_replies WHERE id=?',
                (source_id,),
            ).fetchone()
            if not source or source[0] == author[0] or source[1][:1] not in ('p', 't'):
                return None
            member = c.execute('SELECT wallet_address,username FROM users WHERE id=?', (source[0],)).fetchone()
            if not member or member[0] != wallet:
                return None
            text = _conversation_message(c, d, source, author[0], now)
            previous = learning.prior(c, d, source, author[0])
            context_topic = previous[0] if previous else None
            action_state = _trade_thread_state(c, d, source, author[0]) if context_topic == 'trade_action' else None
            user_id, asker = source[0], member[1]
            thread = chat.thread_context(c, d, source[1], source[4], author[0])
        if not MENTION.search(text):
            return None
        raw = MENTION.sub('', text).strip()
        # Live data, own-account privacy, actions and secrets stay deterministic.
        if not raw or chat.private_request(raw) or prices.query(raw) or public_data.query(raw):
            return None
        deterministic = answer(text, context_topic, action_state=action_state)
        if deterministic and deterministic[0] in chat.DETERMINISTIC_TOPICS:
            return None
    facts = deterministic[1] if deterministic and deterministic[0] not in ('scope', 'welcome', 'overview') else None
    return {'text': text, 'raw': raw, 'asker': asker, 'user_id': user_id, 'thread': thread, 'facts': facts}


def wants_chat(d, source_id, wallet, kind, now=None):
    if not chat.available(d):
        return False
    try:
        return _chat_source(d, source_id, wallet, kind, time.time() if now is None else now) is not None
    except Exception:
        return False


def chat_then_reply(d, source_id, wallet, kind):
    """Background: ask the model, then publish (falls back to the
    deterministic answer when the model gives nothing usable)."""
    try:
        now = time.time()
        src = _chat_source(d, source_id, wallet, kind, now)
        result = None
        if src:
            got = chat.reply(d, src['raw'], src['asker'], src['thread'], src['user_id'], src['facts'], now)
            result = (src['text'], got) if got else None
        if kind == 'post':
            reply_to_post(d, source_id, wallet, chat_answer=result)
        else:
            reply_to(d, source_id, wallet, chat_answer=result)
    except Exception:
        try:
            d.app.logger.exception('orcagent chat reply failed')
        except Exception:
            pass


def member_name(c, user_id):
    row = c.execute('SELECT username FROM users WHERE id=?', (user_id,)).fetchone()
    return row[0] if row and row[0] else 'user'


def _local_brain(text, asker, thread, response):
    """OrcAgent's own conversational answer (orcagent_brain) when no model
    answered: never for live data, actions, secrets or privacy, which their
    deterministic modules own."""
    # Only for a message addressed to OrcAgent (a tag, or a reply in a
    # conversation with it, which _conversation_message prefixes): the
    # deterministic layer answered None for everything else.
    if not isinstance(text, str) or not response or not MENTION.search(text):
        return response
    if response[0] in chat.DETERMINISTIC_TOPICS:
        return response
    raw = MENTION.sub('', text).strip()
    if not raw or chat.private_request(raw) or prices.query(raw) or public_data.query(raw):
        return response
    try:
        local = brain.reply(chat.redact(raw, chat.MAX_QUESTION), asker, thread, response)
    except Exception:
        local = None
    if local:
        clean = chat.safe_output(local[1])
        if clean:
            return (local[0], clean)
    return response


def _privacy_guard(text, response):
    """Absolute: a question about anyone's private account matters is always
    answered with the refusal, whatever any other layer produced."""
    if isinstance(text, str) and chat.private_request(MENTION.sub('', text)):
        return ('privacy', chat.PRIVACY_REFUSAL)
    return response


def reply_to_post(d,post_number,wallet,now=None,chat_answer=None):
    # Only a successfully authenticated NEW post; no edits, reposts or backfill.
    if type(post_number) is not int or post_number<=0:
        return None
    now = time.time() if now is None else now
    market = _prepare_market(d,post_number,wallet,'post',now)
    public = _prepare_public(d,post_number,wallet,'post',now)
    # While the conversational layer is on it owns every model call (with its
    # privacy guard); the older reasoning fallback only runs when it is off.
    reasoning = None if (chat_answer or chat.available(d)) else _prepare_reasoning(d,post_number,wallet,'post',now)
    with sqlite3.connect(d.DB_FILE,timeout=8) as c:
        c.execute('BEGIN IMMEDIATE')
        if not enabled(c,'replies'):
            return None
        author = identity(c)
        if not author:
            return None
        post = c.execute('SELECT wallet,content FROM feed_posts WHERE id=?',(post_number,)).fetchone()
        member = c.execute('SELECT id FROM users WHERE wallet_address=?',(wallet,)).fetchone()
        if not post or post[0]!=wallet or not member or member[0]==author[0]:
            return None
        text = d._feed_text_part(post[1]) if hasattr(d,'_feed_text_part') else re.split(r'__(?:CHART|TRADE|CALL)__',post[1],maxsplit=1)[0]
        response = answer(text,market=_market_for(text,market),public=_public_for(text,public))
        smart = _reasoning_for(text,reasoning)
        if smart and response and smart[0] == response[0]:
            response = smart
        talk = _reasoning_for(text,chat_answer)
        if talk and (not response or response[0] not in chat.DETERMINISTIC_TOPICS):
            response = talk
        elif not talk:
            response = _local_brain(text, member_name(c, member[0]), [], response)
        response = _privacy_guard(text, response)
        key = 'post-reply:'+str(post_number)
        if not response or c.execute('SELECT 1 FROM platform_assistant_events WHERE event_key=?',(key,)).fetchone() or not within_reply_limits(c,member[0],now):
            return None
        topic,message = response
        if enabled(c,'learning'):
            learning.record_contact(
                c,'post',str(post_number),member[0],text,topic,topic,None,MENTION,now
            )
        post_id = 'p'+str(post_number)
        cur = c.execute('INSERT INTO feed_replies(user_id,post_id,message,created_at,parent_reply_id) VALUES(?,?,?,?,NULL)',
                        (author[0],post_id,message,utcstamp(now)))
        c.execute('INSERT INTO platform_assistant_events VALUES(?,?,?,?,?,?,?)',
                  (key,'reply',member[0],post_id,cur.lastrowid,topic,now))
        c.execute('INSERT INTO notifications(user_id,type,content,link,actor_wallet) VALUES(?,?,?,?,?)',
                  (member[0],'reply','OrcAgent replied to you',d._reply_link(c,post_id,cur.lastrowid),author[1]))
        return cur.lastrowid

def reply_to(d, source_id, wallet, now=None, chat_answer=None):
    now = time.time() if now is None else now
    market = _prepare_market(d,source_id,wallet,'reply',now)
    public = _prepare_public(d,source_id,wallet,'reply',now)
    # While the conversational layer is on it owns every model call (with its
    # privacy guard); the older reasoning fallback only runs when it is off.
    reasoning = None if (chat_answer or chat.available(d)) else _prepare_reasoning(d,source_id,wallet,'reply',now)
    with sqlite3.connect(d.DB_FILE, timeout=8) as c:
        c.execute('BEGIN IMMEDIATE')
        if not enabled(c, 'replies'):
            return None
        author = identity(c)
        if not author:
            return None
        source = c.execute('SELECT user_id,post_id,message,created_at,parent_reply_id FROM feed_replies WHERE id=?', (source_id,)).fetchone()
        if not source or source[0] == author[0]:
            return None
        member = c.execute('SELECT wallet_address FROM users WHERE id=?', (source[0],)).fetchone()
        if not member or member[0] != wallet or source[1][:1] not in ('p','t'):
            return None  # Home feed only; never publish private group context.
        created = d._feed_post_created_at(c, source[1])
        if not created or c.execute('SELECT datetime(?)>=datetime(?)', (source[3],created)).fetchone()[0] != 1:
            return None
        use_learning = enabled(c,'learning')
        previous = learning.prior(c,d,source,author[0]) if use_learning else None
        message = _conversation_message(c,d,source,author[0],now)
        action_state = _trade_thread_state(c,d,source,author[0]) if previous and previous[0] == 'trade_action' else None
        explicit = answer(message, previous[0] if previous else None, market=_market_for(message,market), public=_public_for(message,public), action_state=action_state)
        response = explicit
        if explicit and use_learning:
            if explicit[0]=='scope':
                topic = learning.lookup(c,d,source[2],MENTION,LEARNABLE,now)
                clean = MENTION.sub('',source[2])
                if not topic and previous and previous[0] in LEARNABLE and len(clean)<=160 and re.fullmatch(r'\s*(?:how|where|what next|hoe|waar)[\s?!.]*', clean, re.I) and not learning.UNSAFE.search(clean):
                    topic = previous[0]
                if topic:
                    response = topic, LABEL + LEARNABLE[topic]
        smart = _reasoning_for(message,reasoning)
        # Reviewed learned mappings outrank model wording. Otherwise a
        # reasoned answer may refine only the same deterministic intent.
        if smart and response is explicit and explicit and smart[0] == explicit[0]:
            response = smart
        # A conversational answer for anything a deterministic module does
        # not own (live data, actions, secrets, privacy).
        talk = _reasoning_for(message,chat_answer)
        if talk and (not explicit or explicit[0] not in chat.DETERMINISTIC_TOPICS):
            response = talk
        elif not talk:
            response = _local_brain(message, member_name(c, source[0]),
                                    chat.thread_context(c, d, source[1], source[4], author[0]), response)
        response = _privacy_guard(message, response)
        key = 'reply:' + str(source_id)
        if not response or c.execute('SELECT 1 FROM platform_assistant_events WHERE event_key=?', (key,)).fetchone():
            return None
        if not within_reply_limits(c,source[0],now):
            return None
        if use_learning:
            detected = explicit[0] if explicit else None
            learning.record_contact(
                c,'reply',str(source_id),source[0],source[2],detected,response[0],
                previous[0] if previous else None,MENTION,now
            )
            observed = explicit[0] if explicit[0]!='scope' or response[0]=='scope' else None
            learning.observe(c,d,source_id,source,observed,previous,MENTION,LEARNABLE,now)
        topic, message = response
        cur = c.execute('INSERT INTO feed_replies(user_id,post_id,message,created_at,parent_reply_id) VALUES(?,?,?,?,?)',
                        (author[0],source[1],message,utcstamp(now),source_id))
        c.execute('INSERT INTO platform_assistant_events VALUES(?,?,?,?,?,?,?)',
                  (key,'reply',source[0],source[1],cur.lastrowid,topic,now))
        c.execute('INSERT INTO notifications(user_id,type,content,link,actor_wallet) VALUES(?,?,?,?,?)',
                  (source[0],'reply','OrcAgent replied to you',d._reply_link(c,source[1],cur.lastrowid),author[1]))
        return cur.lastrowid

def install(d):
    app = d.app
    if getattr(app, '_orca_platform_assistant', False):
        return
    initialize(d.DB_FILE)
    app._orca_platform_assistant = True
    import ai_key_admin
    ai_key_admin.install(d)

    @app.after_request
    def mentioned(response):
        if request.path not in ('/api/feed/reply','/api/feed/post') or request.method != 'POST' or response.status_code != 200 or not response.is_json:
            return response
        data = response.get_json(silent=True)
        if not isinstance(data,dict) or not data.get('ok') or type(data.get('id')) is not int:
            return response
        try:
            wallet = d._authenticated_wallet()
            if wallet:
                kind = 'post' if request.path=='/api/feed/post' else 'reply'
                if wants_chat(d,data['id'],wallet,kind):
                    # A real conversation takes a few seconds: answer in the
                    # background; the app shows "OrcAgent is typing…" meanwhile.
                    chat.run_later(chat_then_reply,d,data['id'],wallet,kind)
                    data['platform_reply_pending'] = True
                    response.set_data(app.json.dumps(data))
                    return response
                reply_id = reply_to_post(d,data['id'],wallet) if kind=='post' else reply_to(d,data['id'],wallet)
                if reply_id:
                    data['platform_reply_id'] = reply_id
                    response.set_data(app.json.dumps(data))
        except Exception:
            # A bot failure must never turn a successfully saved user reply into an error.
            app.logger.exception('platform assistant reply failed')
        return response

    @app.route('/admin/platform-assistant')
    def settings():
        err = d._require_role('admin','executive')
        if err:
            return err
        with sqlite3.connect(d.DB_FILE,timeout=8) as c:
            author = identity(c)
            state = dict(posts=enabled(c,'posts'),replies=enabled(c,'replies'),learning=enabled(c,'learning'),author=author[2] if author else None)
            import ai_key_admin
            state['ai'] = ai_key_admin.status(d)
            questions = learning.dashboard(c,d,MENTION,LEARNABLE,time.time())
            recent = c.execute('SELECT kind,post_id,reply_id,topic,created_at FROM platform_assistant_events ORDER BY created_at DESC LIMIT 20').fetchall()
        return d._render_no_cache('platform_assistant_admin.html',state=state,recent=recent,theses=THESES,questions=questions,topics=LEARNABLE,csrf_token=d._get_csrf_token())

    @app.route('/api/admin/platform-assistant',methods=['POST'])
    def configure():
        err = d._require_role('admin','executive')
        if err:
            return err
        if not d._validate_csrf(request.headers.get('X-CSRF-Token','')):
            return jsonify(ok=False,error='CSRF validation failed'),403
        body = request.get_json(silent=True)
        if not isinstance(body,dict) or set(body)-{'posts','replies','learning'} or not body or any(type(v) is not bool for v in body.values()):
            return jsonify(ok=False,error='Use boolean posts/replies/learning settings'),400
        with sqlite3.connect(d.DB_FILE,timeout=8) as c:
            c.execute('BEGIN IMMEDIATE')
            for key, value in body.items():
                c.execute('INSERT OR REPLACE INTO platform_assistant_settings VALUES(?,?)',(key,'1' if value else '0'))
        return jsonify(ok=True)

    @app.route('/api/admin/platform-assistant/learning',methods=['POST'])
    def review_learning():
        err = d._require_role('admin','executive')
        if err:
            return err
        if not d._validate_csrf(request.headers.get('X-CSRF-Token','')):
            return jsonify(ok=False,error='CSRF validation failed'),403
        body = request.get_json(silent=True)
        if not isinstance(body,dict) or set(body)-{'question','topic','status'} or any(not isinstance(v,str) for v in body.values()):
            return jsonify(ok=False,error='Invalid review'),400
        wallet = d._authenticated_wallet()
        if not wallet:
            return jsonify(ok=False,error='Authentication required'),401
        try:
            with sqlite3.connect(d.DB_FILE,timeout=8) as c:
                c.execute('BEGIN IMMEDIATE')
                learning.review(c,body.get('question'),body.get('topic'),body.get('status'),wallet,time.time(),LEARNABLE)
        except ValueError as e:
            return jsonify(ok=False,error=str(e)),400
        except LookupError as e:
            return jsonify(ok=False,error=str(e)),404
        return jsonify(ok=True)

    def _trending(d):
        import trending_hero
        return trending_hero.current_trending(d)

    def loop():
        pruned_at = 0.0
        while True:
            if time.time() - pruned_at > 86400:
                pruned_at = time.time()
                try:
                    agent_post_images.prune(d)
                except Exception:
                    app.logger.exception('agent image cleanup failed')
            try:
                publish_due(d.DB_FILE, live_data=lambda: (_trending(d), float(getattr(d, '_sol_price_usd', 0) or 0)),
                            render=lambda media, seed, variant: agent_post_images.make(d, media, seed, variant))
            except Exception:
                app.logger.exception('platform thesis publication failed')
            time.sleep(30)
    threading.Thread(target=loop,name='orca-platform-theses',daemon=True).start()
