const fs=require('fs'),path=require('path'),os=require('os');const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');const root=path.resolve(__dirname,'..'),output=process.env.ORCAGENT_QA_OUTPUT||os.tmpdir();
(async()=>{const b=await chromium.launch({...(process.env.ORCAGENT_CHROMIUM?{executablePath:process.env.ORCAGENT_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});const c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await c.newPage(),errors=[],events=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('http://promo.test/**',r=>{const path=new URL(r.request().url()).pathname;if(path==='/live-market')return r.fulfill({contentType:'text/html; charset=utf-8',body:'<meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#080d11;color:#eef1f5;font-family:system-ui;padding:16px;box-sizing:border-box}.pt-center{width:100%;min-width:0}h1{font-size:25px}</style><main class="pt-center"><header class="pt-feed-hd"><h1>Live Market</h1><p>Live prices · update every second</p></header><div style="color:#32d9a5;margin:16px 0">● SCANNING</div><p>Trending · Gainers · New</p></main>'});if(path==='/api/promote/event'){events.push(JSON.parse(r.request().postData()));return r.fulfill({json:{ok:true}})}return r.fulfill({json:{ok:true,promotions:Array.from({length:5},(_,i)=>({symbol:['STONKINU','Jimothy','EMBER','BONK','Orca'][i],mint:'mint'+i,description:'Discover the community',active:true,demo:true,receipt:'receipt'+i}))}})});
await p.goto('http://promo.test/live-market');
await p.addStyleTag({content:fs.readFileSync(root+'/static/promotions.css','utf8')});
await p.addScriptTag({content:fs.readFileSync(root+'/static/page-lifecycle.js','utf8')});
await p.addScriptTag({content:fs.readFileSync(root+'/static/promotion-placements.js','utf8')});
await p.waitForSelector('.promo-swipe-track .promo-ad');
await p.waitForTimeout(1500);let pos=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);if(pos<10)throw Error('Auto strip did not move '+pos);if(await p.locator('.promo-ad').first().evaluate(e=>e.getBoundingClientRect().height)>85)throw Error('Strip too tall');if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Page overflow');
await p.screenshot({path:path.join(output,'promotion-strip-mobile-qa.png')});
const cd=await c.newCDPSession(p),rect=await p.locator('.promo-swipe-track').boundingBox();const y=rect.y+40;async function swipe(from,to){await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:from,y}]});for(let i=1;i<=8;i++){await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:from+(to-from)*i/8,y}]});
await p.waitForTimeout(18)}await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
await p.waitForTimeout(300)}await swipe(300,90);let left=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);if(left<=pos+80)throw Error('Swipe left failed');
await swipe(100,300);let right=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);if(right>=left-40)throw Error('Swipe right failed');
await p.waitForTimeout(300);let paused=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);
await p.waitForTimeout(700);if(Math.abs(await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft)-paused)>3)throw Error('Auto fought user swipe');
await p.emulateMedia({reducedMotion:'reduce'});
await p.waitForTimeout(5200);let reduced=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);
await p.waitForTimeout(700);if(Math.abs(await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft)-reduced)>2)throw Error('Reduced motion ignored');
await p.emulateMedia({reducedMotion:'no-preference'});
await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft=1485);
await p.waitForTimeout(1000);if(await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft)>1450)throw Error('Loop did not wrap');
await p.getByRole('button',{name:'Pause automatic promotions'}).click();let stopped=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);
await p.waitForTimeout(500);if(Math.abs(await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft)-stopped)>2)throw Error('Pause failed');
await p.setViewportSize({width:1280,height:844});
await p.screenshot({path:path.join(output,'promotion-strip-desktop-qa.png')});const counts={};events.filter(e=>e.event==='view').forEach(e=>counts[e.receipt]=(counts[e.receipt]||0)+1);if(Object.values(counts).some(n=>n>1))throw Error('Duplicate views');
await p.getByRole('button',{name:'Resume automatic promotions'}).click();
await p.evaluate(()=>document.activeElement.blur());
await p.waitForTimeout(5300);const runningLeft=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);
await p.waitForTimeout(300);if(await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft)===runningLeft)throw Error('Resume did not restart motion');
await p.evaluate(()=>OrcPageLifecycle.cleanupRouteScopes('test-navigation'));const cleanupLeft=await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft);
await p.waitForTimeout(500);if(await p.locator('.promo-swipe-track').evaluate(e=>e.scrollLeft)!==cleanupLeft)throw Error('Carousel kept moving after cleanup');if(errors.length)throw Error(errors.join('\n'));console.log('PASS: thin strip, automatic left movement, real touch swipes both ways, interaction pause, reduced motion, seamless wrap, explicit pause, desktop, no page overflow, no duplicate views');
await b.close()})().catch(e=>{console.error(e);process.exit(1)});
