const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('static/dashboard.js','utf8');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ctx={console,Number,String,esc,safeMint:s=>/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(s),_fcRichText:esc,_replyRelTime:()=> 'now'};
vm.createContext(ctx);
vm.runInContext(src.slice(src.indexOf('var _TEAM_ROLE_STYLE ='),src.indexOf('// Only the server',src.indexOf('var _TEAM_ROLE_STYLE ='))),ctx);
vm.runInContext(src.slice(src.indexOf('function _agentPriceReplyHtml('),src.indexOf('async function _assistantTokenChoices(')),ctx);
const mint='98kfF7rmsg1QDUEoCqNE7g7M1FdrTt92TEp2CLzypump';
const quote='PAID: 0.004466 USD · 13:47:22 UTC. Source: DexScreener (retrieved). Solana contract: '+mint+'. https://orcagent.fun/live-market';
const official={id:139,username:'Orcagent',verified:true,team_role:'admin',message:quote};
let html=ctx._renderReplyRow(official,'p554',1);
const visible=html.replace(/<[^>]*>/g,'');
assert.ok(visible.includes('$PAID')&&visible.includes('$0.004466')&&visible.includes('USD'));
assert.ok(visible.includes('AI AGENT'));
for(const text of ['ADMIN','DexScreener','Source:','UTC',mint,'Show more'])assert.ok(!visible.includes(text),text);
assert.ok(html.includes('showTokenCard')&&html.includes(mint),'chart must retain exact selected identity');
assert.ok(!ctx._renderReplyRow({...official,verified:false},'p554',1).includes('fc-agent-price-value'));
assert.ok(ctx._teamBadgeHtml('admin','AnotherUser',true).includes('ADMIN'));
assert.ok(ctx._agentPriceReplyHtml('BTC: 85,873.19 USD · 13:47:22 UTC. Source: Coinbase (updated).').includes('$85,873.19'));
assert.ok(ctx._agentPriceReplyHtml('SOL: 107.70 EUR · 13:47:22 UTC. Source: CoinGecko (updated).').includes('€107.70'));
assert.equal(ctx._agentPriceReplyHtml('BTC: NaN USD · 13:47:22 UTC. Source: Coinbase'), '');
html=ctx._renderReplyRow({id:138,username:'Trader',message:'@orcagent $PAID ('+mint+') what is the price?'},'p554',1);
assert.ok(!html.replace(/<[^>]*>/g,'').includes(mint));
html=ctx._renderReplyRow({...official,message:'Do you mean $PAID? Several Solana tokens match. Choose the right contract below, then send your price question.'},'p554',1);
assert.ok(html.includes('Select the $PAID token.')&&html.includes('Choose $PAID token'));
assert.ok(!html.includes('Several Solana tokens match'));
console.log('PASS compact legacy/current quotes, exact-token chart action, identity badge, native currencies, invalid price and compact chooser');
if(process.env.AGENT_PREVIEW){
 fs.writeFileSync(process.env.AGENT_PREVIEW,ctx._renderReplyRow({id:136,username:'degentrader1990',verified:true,team_role:'executive',is_mine:true,message:'@orcagent what is the price of $paid'},'p554',0)+ctx._renderReplyRow({...official,id:137,message:'Do you mean $PAID? Several Solana tokens match. Choose the right contract below, then send your price question.'},'p554',1)+ctx._renderReplyRow({id:138,username:'degentrader1990',verified:true,team_role:'executive',is_mine:true,message:'@orcagent $PAID ('+mint+') what is the price?'},'p554',1)+ctx._renderReplyRow(official,'p554',1));
}
