const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const css=fs.readFileSync('static/mobile-bottom-nav.css','utf8');
const home=fs.readFileSync('dashboard.html','utf8');
const boot=fs.readFileSync('static/navbar.js','utf8');
const js=fs.readFileSync('static/mobile-bottom-nav.js','utf8');
assert.match(css,/\.oa-bottom-nav\{[^}]*position:fixed!important;[^}]*bottom:0!important;[^}]*box-sizing:border-box!important/);
assert(!css.includes('box-sizing:content-box'));
assert(home.includes('viewport-fit=cover'));
assert(boot.includes('mobile-bottom-nav.css?v=4'));
assert(boot.includes('mobile-bottom-nav.js?v=5'));
const start=js.indexOf('var _dockFrame=0;'),end=js.indexOf('function build(){',start);
assert(start>=0&&end>start);
let shift=0,changes=0;
const nav={dataset:{},style:{setProperty(key,value,priority){assert.equal(key,'transform');assert.equal(priority,'important');shift=Number(value.match(/translate3d\(0,(-?[\d.]+)px/)[1]);changes++}},getClientRects(){return [1]},getBoundingClientRect(){return {bottom:734+shift}}};
const vv={offsetTop:0,height:760};
const ctx={window:{visualViewport:vv,matchMedia:()=>({matches:true})},document:{getElementById:()=>nav},Number,Math,requestAnimationFrame:fn=>{fn();return 1}};
vm.createContext(ctx);vm.runInContext(js.slice(start,end),ctx);
ctx._dockBottomNav();
assert.equal(shift,26,'nav must close a measured 26px viewport gap');
ctx._dockBottomNav();
assert.equal(changes,1,'aligned navbar must not jitter or re-transform');
vv.height=720;
ctx._dockBottomNav();
assert.equal(shift,-14,'nav must re-dock after browser chrome changes');
vv.height=400;
ctx._dockBottomNav();
assert.equal(shift,-14,'keyboard-scale displacement must not move footer over input');
console.log('PASS mobile footer: border-box safe area, cache-busted scripts, live viewport docking, no jitter, keyboard guard');
