const fs=require('fs'),assert=require('assert');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{const root=require('path').resolve(__dirname,'..');const browser=await chromium.launch({executablePath:process.env.ORCAGENT_CHROMIUM||undefined,args:['--no-sandbox','--disable-gpu','--no-zygote']});
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});let release;const gate=new Promise(r=>release=r);let errors=[];page.on('pageerror',e=>errors.push(String(e)));
const messages=Array.from({length:45},(_,i)=>({id:i+1,sender_id:2,sender:'Bob',sender_wallet:'bob',sender_avatar:'',kind:i===43?'image':'text',body:i===43?'https://group.test/photo.svg':'Message '+i,mine:false,created_at:'2026-10-10 04:00:00',version:0,likes:[],liked:false}));
await page.route('https://group.test/**',async r=>{const path=new URL(r.request().url()).pathname;if(path==='/photo.svg'){await gate;await r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="300" height="340"><rect width="300" height="340" fill="green"/></svg>'});return;}let data=path.endsWith('/messages')?{ok:true,messages}:path==='/api/group-chats/1'?{ok:true,chat:{id:1,name:'Test',members:[],role:'member',created_by:2}}:{ok:true,chats:[]};await r.fulfill({contentType:path==='/'?'text/html':'application/json',body:path==='/'?'<div id="conv-list"></div>':JSON.stringify(data)});});
await page.goto('https://group.test/');await page.addStyleTag({content:fs.readFileSync(root+'/static/group-chats.css','utf8')});await page.addScriptTag({content:fs.readFileSync(root+'/static/page-lifecycle.js','utf8')});await page.addScriptTag({content:fs.readFileSync(root+'/static/chat-tips.js','utf8')});await page.addScriptTag({content:fs.readFileSync(root+'/static/group-chats.js','utf8')});await page.evaluate(()=>OrcAgentGroupChats.open(1,false));await page.waitForSelector('[data-mid="45"]');const gap=()=>page.evaluate(()=>{const b=document.querySelector('.gc-th-body');return b.scrollHeight-b.scrollTop-b.clientHeight;});assert(await gap()<2,'initial bottom');release();await page.waitForFunction(()=>document.querySelector('.gc-img').naturalHeight>0);await page.waitForTimeout(100);assert(await gap()<2,'late photo bottom');
await page.evaluate(()=>{const b=document.querySelector('.gc-th-body');b.dispatchEvent(new Event('touchstart'));b.scrollTop=100;});await page.waitForTimeout(50);const top=await page.evaluate(()=>document.querySelector('.gc-th-body').scrollTop);await page.evaluate(()=>{document.querySelector('.gc-img').style.height='180px';});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.querySelector('.gc-th-body').scrollTop),top,'preserve older reading');
await page.evaluate(()=>OrcAgentGroupChats.open(1,false));await page.waitForTimeout(100);assert(await gap()<2,'reopen bottom');assert.deepEqual(errors,[]);await browser.close();console.log('PASS initial latest message, delayed photo, preserve manual scroll, reopen latest, no errors');})();
